### ISSUE TITLE
Other windows are no longer restored

### ISSUE THREAD

**Issue by veselov** [babyman/quick-tabs-chrome-extension#232]
Currently running 2017.10.8 in 70.0.3538.102 on Fedora+KDE.
Everything was perfect until switching to Chrome 70.
Now, if I want to switch to a tab that is in a window different from where I'm searching for it, and that window is minimized, then the window doesn't restore. The window does change its current tab, though, if it wasn't on the tab I asked to switch to. I can't capture any errors from the console, as it closes immediately when I select the tab.

When I try to do the same from Chrome itself (it has sort of support for this, when you type something in URL, and there is an open tab, there is a button to go to that tab), the window does restore properly.

Specifically, to reproduce:
Open browser window (1), navigate to site A
Open another tab on the same window, navigate to site B
Open another browser window (2), and minimize window 1
While in window 2, open quick tab extension and search for site A, click to open the found tab.

Observe: window 1 remains in the background, even though though it switched to site A

**Comment by jasonzhao3** [comment]
+1 . After upgrading to Chrome 70, I also experience the similar issue.

**Comment by briantully** [comment]
+1 definitely seems that Chrome 70 has introduced some new code that breaks some functionality of the Quick Tabs extension.

**Comment by MartinLichtblau** [comment]
Linux only? Since on my Windows it works.

**Comment by JoelAzaria** [comment]
On Chrome 71 64b, Win 10.  I can't reproduce.  Possible was a bug in 70 and fixed in 71?  @veselov

**Comment by veselov** [comment]
This is probably a Linux-only problem. It's still happening on 71.0.3578.98.

**Comment by JoelAzaria** [comment]
Strange.  Maybe combo of extensions too.  Try disabling all but QT and see if problem persists?  
Or maybe try removing and reinstalling QT?

Shots in the dark but may be worth a try...

**Comment by MartinLichtblau** [comment]
@veselov could you try out whether the new Pull-Request solves it?

**Comment by veselov** [comment]
@MartinLichtblau Didn't make a difference, sorry. I see the same issue of having the tab switch on the minimized window, but it doesn't restore from being minimized. Using Version 72.0.3626.81 (Official Build) (64-bit) now. I checked. I honestly think it's a bug in Chrome, but I don't know enough about which APIs are being used to complain to them. I see the same problem with, say, pop-up notifications for some services that should bring the window/tab up when you click on it (e.g. web.whatsapp.com).

**Comment by onurabi** [comment]
Have the same problem in Linux, using version 72.0.3626.121. 

But I also see the same problematic behavior in Chrome profiles. Switching from one profile to another doesn't bring the relevant windows in focus. It used to work that way.

**Comment by MartinLichtblau** [comment]
So, it really is a [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=921290). I changed the code nevertheless and switching goes much smoother now. So I'll do a PR anyway.

But how to deal with this bug? Is the "Switch to this tab" function inside the Omnibar really working?

**Comment by veselov** [comment]
Whatever the problem was, it looks like it has been fixed. The windows restore and focus on 73.0.3683.103. I'm running latest FC29 if that matters
